### ISSUE TITLE
Editing fields is a little funky.

### ISSUE THREAD

**Issue by rgleason** [RooieDirk/Deviation_pi#4]
You seem to have to delete numbers in order to enter them.
There is a certain specified number of digits required, no greater is not allowed.
This makes editing numbers a little repetitive and strange.

Is there a better way to do it?

**Comment by RooieDirk** [comment]
Yes I am aware. This is mostly because, for a new entry, the PI is updating values from incoming (nmea) data until the first enty is manual changed. I did this in order to have an electronic compass reading updated without the need for entering data.
Or in case you change to a sun azimuth the time is updated again upto the current time (and also the true bearing).
But coming week I planned an upgrade of the logic behind this.
